# Generated by Django 6.0.4 on 2026-05-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_tournament_organizer_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Tournament Organizer')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mycalendar', '0003_profile_days_available_profile_fun_facts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_tournament_organizer_group, migrations.RunPython.noop),
    ]
