# Generated by Django 6.0.4 on 2026-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_url',
            field=models.URLField(blank=True),
        ),
    ]
