# Generated by Django 6.0.4 on 2026-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0005_event_start_time_event_twitch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='twitch_broadcaster_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_live_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_stream_game_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_stream_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='twitch_viewer_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
